### ISSUE TITLE
Any tutorials or instructions on how to implement this on Windows?

### ISSUE THREAD

**Issue by luiandresgonzalez** [robjhyndman/MonashWP#3]
I've downloaded all the source files, but I don't understand clearly how to implement this on Windows 10. Any help or tutorial for novices on how to apply this kind of tables in RStudio on Windows?

Thank you very much!

**Comment by robjhyndman** [comment]
You need to have MikTeX installed as well as R and the required R packages. After that, it should work within RStudio.
